# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule TelnyxAPI.Model.AnswerRequest do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"billing_group_id",
    :"client_state",
    :"command_id",
    :"webhook_url",
    :"webhook_url_method"
  ]

  @type t :: %__MODULE__{
    :"billing_group_id" => String.t | nil,
    :"client_state" => String.t | nil,
    :"command_id" => String.t | nil,
    :"webhook_url" => String.t | nil,
    :"webhook_url_method" => String.t | nil
  }
end

defimpl Poison.Decoder, for: TelnyxAPI.Model.AnswerRequest do
  def decode(value, _options) do
    value
  end
end

