# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule TelnyxAPI.Model.CallForkStartedPayload do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"connection_id",
    :"call_leg_id",
    :"call_session_id"
  ]

  @type t :: %__MODULE__{
    :"connection_id" => String.t | nil,
    :"call_leg_id" => String.t | nil,
    :"call_session_id" => String.t | nil
  }
end

defimpl Poison.Decoder, for: TelnyxAPI.Model.CallForkStartedPayload do
  def decode(value, _options) do
    value
  end
end

