# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule TelnyxAPI.Model.CallRecordingSavedPayloadPublicRecordingUrls do
  @moduledoc """
  Recording URLs in requested format. The URL is valid for as long as the file exists. For security purposes, this feature is activated on a per request basis.  Please contact customer support with your Account ID to request activation.
  """

  @derive [Poison.Encoder]
  defstruct [
    :"mp3",
    :"wav"
  ]

  @type t :: %__MODULE__{
    :"mp3" => String.t | nil,
    :"wav" => String.t | nil
  }
end

defimpl Poison.Decoder, for: TelnyxAPI.Model.CallRecordingSavedPayloadPublicRecordingUrls do
  def decode(value, _options) do
    value
  end
end

