# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule TelnyxAPI.Model.CallRecordingSavedPayloadRecordingUrls do
  @moduledoc """
  Recording URLs in requested format. These URLs are valid for 10 minutes. After 10 minutes, you may retrieve recordings via API using Reports -> Call Recordings documentation, or via Mission Control under Reporting -> Recordings.
  """

  @derive [Poison.Encoder]
  defstruct [
    :"mp3",
    :"wav"
  ]

  @type t :: %__MODULE__{
    :"mp3" => String.t | nil,
    :"wav" => String.t | nil
  }
end

defimpl Poison.Decoder, for: TelnyxAPI.Model.CallRecordingSavedPayloadRecordingUrls do
  def decode(value, _options) do
    value
  end
end

