# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule TelnyxAPI.Model.CallControlApplication do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"active",
    :"anchorsite_override",
    :"application_name",
    :"created_at",
    :"dtmf_type",
    :"first_command_timeout",
    :"first_command_timeout_secs",
    :"id",
    :"inbound",
    :"outbound",
    :"record_type",
    :"updated_at",
    :"webhook_api_version",
    :"webhook_event_failover_url",
    :"webhook_event_url",
    :"webhook_timeout_secs"
  ]

  @type t :: %__MODULE__{
    :"active" => boolean() | nil,
    :"anchorsite_override" => String.t | nil,
    :"application_name" => String.t | nil,
    :"created_at" => String.t | nil,
    :"dtmf_type" => String.t | nil,
    :"first_command_timeout" => boolean() | nil,
    :"first_command_timeout_secs" => integer() | nil,
    :"id" => String.t | nil,
    :"inbound" => TelnyxAPI.Model.CallControlApplicationInbound.t | nil,
    :"outbound" => TelnyxAPI.Model.CallControlApplicationOutbound.t | nil,
    :"record_type" => String.t | nil,
    :"updated_at" => String.t | nil,
    :"webhook_api_version" => String.t | nil,
    :"webhook_event_failover_url" => String.t | nil,
    :"webhook_event_url" => String.t | nil,
    :"webhook_timeout_secs" => integer() | nil
  }
end

defimpl Poison.Decoder, for: TelnyxAPI.Model.CallControlApplication do
  import TelnyxAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"inbound", :struct, TelnyxAPI.Model.CallControlApplicationInbound, options)
    |> deserialize(:"outbound", :struct, TelnyxAPI.Model.CallControlApplicationOutbound, options)
  end
end

