# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule TelnyxAPI.Model.CallEvent do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"record_type",
    :"call_leg_id",
    :"call_session_id",
    :"event_timestamp",
    :"name",
    :"type",
    :"metadata"
  ]

  @type t :: %__MODULE__{
    :"record_type" => String.t,
    :"call_leg_id" => String.t,
    :"call_session_id" => String.t,
    :"event_timestamp" => String.t,
    :"name" => String.t,
    :"type" => String.t,
    :"metadata" => map()
  }
end

defimpl Poison.Decoder, for: TelnyxAPI.Model.CallEvent do
  def decode(value, _options) do
    value
  end
end

