# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule TelnyxAPI.Model.CallLeftQueuePayload do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"call_control_id",
    :"connection_id",
    :"call_leg_id",
    :"call_session_id",
    :"client_state",
    :"queue",
    :"queue_position",
    :"reason"
  ]

  @type t :: %__MODULE__{
    :"call_control_id" => String.t | nil,
    :"connection_id" => String.t | nil,
    :"call_leg_id" => String.t | nil,
    :"call_session_id" => String.t | nil,
    :"client_state" => String.t | nil,
    :"queue" => String.t | nil,
    :"queue_position" => integer() | nil,
    :"reason" => String.t | nil
  }
end

defimpl Poison.Decoder, for: TelnyxAPI.Model.CallLeftQueuePayload do
  def decode(value, _options) do
    value
  end
end

