# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule TelnyxAPI.Model.Call do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"record_type",
    :"call_session_id",
    :"call_leg_id",
    :"call_control_id",
    :"is_alive"
  ]

  @type t :: %__MODULE__{
    :"record_type" => String.t,
    :"call_session_id" => String.t,
    :"call_leg_id" => String.t,
    :"call_control_id" => String.t,
    :"is_alive" => boolean()
  }
end

defimpl Poison.Decoder, for: TelnyxAPI.Model.Call do
  def decode(value, _options) do
    value
  end
end

