# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule TelnyxAPI.Model.ConferenceSpeakRequest do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"call_control_ids",
    :"payload",
    :"payload_type",
    :"voice",
    :"language",
    :"command_id"
  ]

  @type t :: %__MODULE__{
    :"call_control_ids" => [String.t] | nil,
    :"payload" => String.t,
    :"payload_type" => String.t | nil,
    :"voice" => String.t,
    :"language" => String.t,
    :"command_id" => String.t | nil
  }
end

defimpl Poison.Decoder, for: TelnyxAPI.Model.ConferenceSpeakRequest do
  def decode(value, _options) do
    value
  end
end

