# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule TelnyxAPI.Model.ConferenceParticipantSpeakStartedPayload do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"call_control_id",
    :"call_leg_id",
    :"call_session_id",
    :"client_state",
    :"connection_id",
    :"creator_call_session_id",
    :"conference_id",
    :"occurred_at"
  ]

  @type t :: %__MODULE__{
    :"call_control_id" => String.t | nil,
    :"call_leg_id" => String.t | nil,
    :"call_session_id" => String.t | nil,
    :"client_state" => String.t | nil,
    :"connection_id" => String.t | nil,
    :"creator_call_session_id" => String.t | nil,
    :"conference_id" => String.t | nil,
    :"occurred_at" => DateTime.t | nil
  }
end

defimpl Poison.Decoder, for: TelnyxAPI.Model.ConferenceParticipantSpeakStartedPayload do
  def decode(value, _options) do
    value
  end
end

