# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule TelnyxAPI.Model.ConferenceRecordingSavedPayload do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"call_control_id",
    :"channels",
    :"conference_id",
    :"connection_id",
    :"format",
    :"public_recording_urls",
    :"recording_ended_at",
    :"recording_id",
    :"recording_started_at",
    :"recording_urls"
  ]

  @type t :: %__MODULE__{
    :"call_control_id" => String.t | nil,
    :"channels" => String.t | nil,
    :"conference_id" => String.t | nil,
    :"connection_id" => String.t | nil,
    :"format" => String.t | nil,
    :"public_recording_urls" => TelnyxAPI.Model.CallRecordingSavedPayloadPublicRecordingUrls.t | nil,
    :"recording_ended_at" => DateTime.t | nil,
    :"recording_id" => String.t | nil,
    :"recording_started_at" => DateTime.t | nil,
    :"recording_urls" => TelnyxAPI.Model.CallRecordingSavedPayloadRecordingUrls.t | nil
  }
end

defimpl Poison.Decoder, for: TelnyxAPI.Model.ConferenceRecordingSavedPayload do
  import TelnyxAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"public_recording_urls", :struct, TelnyxAPI.Model.CallRecordingSavedPayloadPublicRecordingUrls, options)
    |> deserialize(:"recording_urls", :struct, TelnyxAPI.Model.CallRecordingSavedPayloadRecordingUrls, options)
  end
end

