# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule TelnyxAPI.Model.ConferenceEndedBy do
  @moduledoc """
  IDs related to who ended the conference. It is expected for them to all be there or all be null
  """

  @derive [Poison.Encoder]
  defstruct [
    :"call_control_id",
    :"call_session_id"
  ]

  @type t :: %__MODULE__{
    :"call_control_id" => String.t | nil,
    :"call_session_id" => String.t | nil
  }
end

defimpl Poison.Decoder, for: TelnyxAPI.Model.ConferenceEndedBy do
  def decode(value, _options) do
    value
  end
end

