# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule TelnyxAPI.Model.ConferenceUnholdRequest do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"call_control_ids"
  ]

  @type t :: %__MODULE__{
    :"call_control_ids" => [String.t]
  }
end

defimpl Poison.Decoder, for: TelnyxAPI.Model.ConferenceUnholdRequest do
  def decode(value, _options) do
    value
  end
end

