# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule TelnyxAPI.Model.ConferencePlayRequest do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"audio_url",
    :"media_name",
    :"loop",
    :"call_control_ids"
  ]

  @type t :: %__MODULE__{
    :"audio_url" => String.t | nil,
    :"media_name" => String.t | nil,
    :"loop" => TelnyxAPI.Model.Loopcount.t | nil,
    :"call_control_ids" => [String.t] | nil
  }
end

defimpl Poison.Decoder, for: TelnyxAPI.Model.ConferencePlayRequest do
  import TelnyxAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"loop", :struct, TelnyxAPI.Model.Loopcount, options)
  end
end

