# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule TelnyxAPI.Model.CreateMessageRequest do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"from",
    :"messaging_profile_id",
    :"to",
    :"text",
    :"subject",
    :"media_urls",
    :"webhook_url",
    :"webhook_failover_url",
    :"use_profile_webhooks",
    :"type",
    :"auto_detect"
  ]

  @type t :: %__MODULE__{
    :"from" => String.t | nil,
    :"messaging_profile_id" => String.t | nil,
    :"to" => String.t,
    :"text" => String.t | nil,
    :"subject" => String.t | nil,
    :"media_urls" => [String.t] | nil,
    :"webhook_url" => String.t | nil,
    :"webhook_failover_url" => String.t | nil,
    :"use_profile_webhooks" => boolean() | nil,
    :"type" => String.t | nil,
    :"auto_detect" => boolean() | nil
  }
end

defimpl Poison.Decoder, for: TelnyxAPI.Model.CreateMessageRequest do
  def decode(value, _options) do
    value
  end
end

