# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule TelnyxAPI.Model.CustomSipHeader do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"name",
    :"value"
  ]

  @type t :: %__MODULE__{
    :"name" => String.t,
    :"value" => String.t
  }
end

defimpl Poison.Decoder, for: TelnyxAPI.Model.CustomSipHeader do
  def decode(value, _options) do
    value
  end
end

