# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule TelnyxAPI.Model.EnqueueRequest do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"queue_name",
    :"client_state",
    :"command_id",
    :"max_wait_time_secs",
    :"max_size"
  ]

  @type t :: %__MODULE__{
    :"queue_name" => String.t | nil,
    :"client_state" => String.t | nil,
    :"command_id" => String.t | nil,
    :"max_wait_time_secs" => integer() | nil,
    :"max_size" => integer() | nil
  }
end

defimpl Poison.Decoder, for: TelnyxAPI.Model.EnqueueRequest do
  def decode(value, _options) do
    value
  end
end

