# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule TelnyxAPI.Model.ErrorSource do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"pointer",
    :"parameter"
  ]

  @type t :: %__MODULE__{
    :"pointer" => String.t | nil,
    :"parameter" => String.t | nil
  }
end

defimpl Poison.Decoder, for: TelnyxAPI.Model.ErrorSource do
  def decode(value, _options) do
    value
  end
end

