# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule TelnyxAPI.Model.Errors do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"errors"
  ]

  @type t :: %__MODULE__{
    :"errors" => [TelnyxAPI.Model.Error.t] | nil
  }
end

defimpl Poison.Decoder, for: TelnyxAPI.Model.Errors do
  import TelnyxAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"errors", :list, TelnyxAPI.Model.Error, options)
  end
end

