# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule TelnyxAPI.Model.GatherUsingSpeakRequest do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"payload",
    :"invalid_payload",
    :"payload_type",
    :"service_level",
    :"voice",
    :"language",
    :"minimum_digits",
    :"maximum_digits",
    :"maximum_tries",
    :"timeout_millis",
    :"terminating_digit",
    :"valid_digits",
    :"inter_digit_timeout_millis",
    :"client_state",
    :"command_id"
  ]

  @type t :: %__MODULE__{
    :"payload" => String.t,
    :"invalid_payload" => String.t | nil,
    :"payload_type" => String.t | nil,
    :"service_level" => String.t | nil,
    :"voice" => String.t,
    :"language" => String.t,
    :"minimum_digits" => integer() | nil,
    :"maximum_digits" => integer() | nil,
    :"maximum_tries" => integer() | nil,
    :"timeout_millis" => integer() | nil,
    :"terminating_digit" => String.t | nil,
    :"valid_digits" => String.t | nil,
    :"inter_digit_timeout_millis" => integer() | nil,
    :"client_state" => String.t | nil,
    :"command_id" => String.t | nil
  }
end

defimpl Poison.Decoder, for: TelnyxAPI.Model.GatherUsingSpeakRequest do
  def decode(value, _options) do
    value
  end
end

