# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule TelnyxAPI.Model.HostedNumber do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"record_type",
    :"id",
    :"phone_number",
    :"status"
  ]

  @type t :: %__MODULE__{
    :"record_type" => String.t | nil,
    :"id" => String.t | nil,
    :"phone_number" => String.t | nil,
    :"status" => String.t | nil
  }
end

defimpl Poison.Decoder, for: TelnyxAPI.Model.HostedNumber do
  def decode(value, _options) do
    value
  end
end

