# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule TelnyxAPI.Model.InboundMessagePayload do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"record_type",
    :"direction",
    :"id",
    :"type",
    :"messaging_profile_id",
    :"to",
    :"cc",
    :"from",
    :"text",
    :"media",
    :"webhook_url",
    :"webhook_failover_url",
    :"encoding",
    :"parts",
    :"tags",
    :"cost",
    :"received_at",
    :"sent_at",
    :"completed_at",
    :"valid_until",
    :"errors"
  ]

  @type t :: %__MODULE__{
    :"record_type" => String.t | nil,
    :"direction" => String.t | nil,
    :"id" => String.t | nil,
    :"type" => String.t | nil,
    :"messaging_profile_id" => String.t | nil,
    :"to" => [TelnyxAPI.Model.InboundMessagePayloadTo.t] | nil,
    :"cc" => [TelnyxAPI.Model.InboundMessagePayloadCc.t] | nil,
    :"from" => TelnyxAPI.Model.InboundMessagePayloadFrom.t | nil,
    :"text" => String.t | nil,
    :"media" => [TelnyxAPI.Model.InboundMessagePayloadMedia.t] | nil,
    :"webhook_url" => String.t | nil,
    :"webhook_failover_url" => String.t | nil,
    :"encoding" => String.t | nil,
    :"parts" => integer() | nil,
    :"tags" => [String.t] | nil,
    :"cost" => TelnyxAPI.Model.InboundMessagePayloadCost.t | nil,
    :"received_at" => DateTime.t | nil,
    :"sent_at" => DateTime.t | nil,
    :"completed_at" => DateTime.t | nil,
    :"valid_until" => DateTime.t | nil,
    :"errors" => [TelnyxAPI.Model.Error.t] | nil
  }
end

defimpl Poison.Decoder, for: TelnyxAPI.Model.InboundMessagePayload do
  import TelnyxAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"to", :list, TelnyxAPI.Model.InboundMessagePayloadTo, options)
    |> deserialize(:"cc", :list, TelnyxAPI.Model.InboundMessagePayloadCc, options)
    |> deserialize(:"from", :struct, TelnyxAPI.Model.InboundMessagePayloadFrom, options)
    |> deserialize(:"media", :list, TelnyxAPI.Model.InboundMessagePayloadMedia, options)
    |> deserialize(:"cost", :struct, TelnyxAPI.Model.InboundMessagePayloadCost, options)
    |> deserialize(:"errors", :list, TelnyxAPI.Model.Error, options)
  end
end

