# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule TelnyxAPI.Model.LeaveConferenceRequest do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"call_control_id",
    :"command_id",
    :"beep_enabled"
  ]

  @type t :: %__MODULE__{
    :"call_control_id" => String.t,
    :"command_id" => String.t | nil,
    :"beep_enabled" => String.t | nil
  }
end

defimpl Poison.Decoder, for: TelnyxAPI.Model.LeaveConferenceRequest do
  def decode(value, _options) do
    value
  end
end

