# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule TelnyxAPI.Model.MessagingProfileHighLevelMetrics do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"record_type",
    :"messaging_profile_id",
    :"phone_numbers",
    :"outbound",
    :"inbound"
  ]

  @type t :: %__MODULE__{
    :"record_type" => String.t | nil,
    :"messaging_profile_id" => String.t | nil,
    :"phone_numbers" => float() | nil,
    :"outbound" => TelnyxAPI.Model.MessagingProfileHighLevelMetricsOutbound.t | nil,
    :"inbound" => TelnyxAPI.Model.MessagingProfileHighLevelMetricsInbound.t | nil
  }
end

defimpl Poison.Decoder, for: TelnyxAPI.Model.MessagingProfileHighLevelMetrics do
  import TelnyxAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"outbound", :struct, TelnyxAPI.Model.MessagingProfileHighLevelMetricsOutbound, options)
    |> deserialize(:"inbound", :struct, TelnyxAPI.Model.MessagingProfileHighLevelMetricsInbound, options)
  end
end

