# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule TelnyxAPI.Model.MessagingHostedNumberOrder do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"record_type",
    :"id",
    :"messaging_profile_id",
    :"status",
    :"phone_numbers"
  ]

  @type t :: %__MODULE__{
    :"record_type" => String.t | nil,
    :"id" => String.t | nil,
    :"messaging_profile_id" => String.t | nil,
    :"status" => String.t | nil,
    :"phone_numbers" => [TelnyxAPI.Model.HostedNumber.t] | nil
  }
end

defimpl Poison.Decoder, for: TelnyxAPI.Model.MessagingHostedNumberOrder do
  import TelnyxAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"phone_numbers", :list, TelnyxAPI.Model.HostedNumber, options)
  end
end

