# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule TelnyxAPI.Model.MessagingFeatureSet do
  @moduledoc """
  The set of features available for a specific messaging use case (SMS or MMS). Features can vary depending on the characteristics the phone number, as well as its current product configuration. 
  """

  @derive [Poison.Encoder]
  defstruct [
    :"domestic_two_way",
    :"international_inbound",
    :"international_outbound"
  ]

  @type t :: %__MODULE__{
    :"domestic_two_way" => boolean(),
    :"international_inbound" => boolean(),
    :"international_outbound" => boolean()
  }
end

defimpl Poison.Decoder, for: TelnyxAPI.Model.MessagingFeatureSet do
  def decode(value, _options) do
    value
  end
end

