# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule TelnyxAPI.Model.MessagingProfileHighLevelMetricsInbound do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"received"
  ]

  @type t :: %__MODULE__{
    :"received" => float() | nil
  }
end

defimpl Poison.Decoder, for: TelnyxAPI.Model.MessagingProfileHighLevelMetricsInbound do
  def decode(value, _options) do
    value
  end
end

