# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule TelnyxAPI.Model.MessagingProfileHighLevelMetricsOutbound do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"sent",
    :"delivered",
    :"error_ratio"
  ]

  @type t :: %__MODULE__{
    :"sent" => float() | nil,
    :"delivered" => float() | nil,
    :"error_ratio" => float() | nil
  }
end

defimpl Poison.Decoder, for: TelnyxAPI.Model.MessagingProfileHighLevelMetricsOutbound do
  def decode(value, _options) do
    value
  end
end

