# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule TelnyxAPI.Model.MessagingProfile do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"record_type",
    :"id",
    :"name",
    :"enabled",
    :"webhook_url",
    :"webhook_failover_url",
    :"webhook_api_version",
    :"whitelisted_destinations",
    :"created_at",
    :"updated_at",
    :"v1_secret",
    :"number_pool_settings",
    :"url_shortener_settings"
  ]

  @type t :: %__MODULE__{
    :"record_type" => String.t | nil,
    :"id" => String.t | nil,
    :"name" => String.t | nil,
    :"enabled" => boolean() | nil,
    :"webhook_url" => String.t | nil,
    :"webhook_failover_url" => String.t | nil,
    :"webhook_api_version" => String.t | nil,
    :"whitelisted_destinations" => [String.t] | nil,
    :"created_at" => DateTime.t | nil,
    :"updated_at" => DateTime.t | nil,
    :"v1_secret" => String.t | nil,
    :"number_pool_settings" => TelnyxAPI.Model.NumberPoolSettings.t | nil,
    :"url_shortener_settings" => TelnyxAPI.Model.UrlShortenerSettings.t | nil
  }
end

defimpl Poison.Decoder, for: TelnyxAPI.Model.MessagingProfile do
  import TelnyxAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"number_pool_settings", :struct, TelnyxAPI.Model.NumberPoolSettings, options)
    |> deserialize(:"url_shortener_settings", :struct, TelnyxAPI.Model.UrlShortenerSettings, options)
  end
end

