# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule TelnyxAPI.Model.MessagingProfileMessageTypeMetrics do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"label",
    :"sent",
    :"delivered",
    :"outbound_error_ratio",
    :"received"
  ]

  @type t :: %__MODULE__{
    :"label" => String.t | nil,
    :"sent" => float() | nil,
    :"delivered" => float() | nil,
    :"outbound_error_ratio" => float() | nil,
    :"received" => float() | nil
  }
end

defimpl Poison.Decoder, for: TelnyxAPI.Model.MessagingProfileMessageTypeMetrics do
  def decode(value, _options) do
    value
  end
end

