# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule TelnyxAPI.Model.MessagingProfileDetailedMetric do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"timestamp",
    :"metrics"
  ]

  @type t :: %__MODULE__{
    :"timestamp" => String.t | nil,
    :"metrics" => [TelnyxAPI.Model.MessagingProfileMessageTypeMetrics.t] | nil
  }
end

defimpl Poison.Decoder, for: TelnyxAPI.Model.MessagingProfileDetailedMetric do
  import TelnyxAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"metrics", :list, TelnyxAPI.Model.MessagingProfileMessageTypeMetrics, options)
  end
end

