# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule TelnyxAPI.Model.MessagingUrlDomain do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"record_type",
    :"id",
    :"url_domain",
    :"use_case"
  ]

  @type t :: %__MODULE__{
    :"record_type" => String.t | nil,
    :"id" => String.t | nil,
    :"url_domain" => String.t | nil,
    :"use_case" => String.t | nil
  }
end

defimpl Poison.Decoder, for: TelnyxAPI.Model.MessagingUrlDomain do
  def decode(value, _options) do
    value
  end
end

