# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule TelnyxAPI.Model.NumberPoolSettings do
  @moduledoc """
  Number Pool allows you to send messages from a pool of numbers of different types, assigning weights to each type. The pool consists of all the long code and toll free numbers assigned to the messaging profile.  To disable this feature, set the object field to `null`. 
  """

  @derive [Poison.Encoder]
  defstruct [
    :"toll_free_weight",
    :"long_code_weight",
    :"skip_unhealthy",
    :"sticky_sender",
    :"geomatch"
  ]

  @type t :: %__MODULE__{
    :"toll_free_weight" => float(),
    :"long_code_weight" => float(),
    :"skip_unhealthy" => boolean(),
    :"sticky_sender" => boolean() | nil,
    :"geomatch" => boolean() | nil
  }
end

defimpl Poison.Decoder, for: TelnyxAPI.Model.NumberPoolSettings do
  def decode(value, _options) do
    value
  end
end

