# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule TelnyxAPI.Model.NumberHealthMetrics do
  @moduledoc """
  High level health metrics about the number and it's messaging sending patterns. 
  """

  @derive [Poison.Encoder]
  defstruct [
    :"message_count",
    :"inbound_outbound_ratio",
    :"success_ratio",
    :"spam_ratio"
  ]

  @type t :: %__MODULE__{
    :"message_count" => integer(),
    :"inbound_outbound_ratio" => float(),
    :"success_ratio" => float(),
    :"spam_ratio" => float()
  }
end

defimpl Poison.Decoder, for: TelnyxAPI.Model.NumberHealthMetrics do
  def decode(value, _options) do
    value
  end
end

