# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule TelnyxAPI.Model.OutboundMessagePayloadMedia do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"url",
    :"content_type",
    :"sha256",
    :"size"
  ]

  @type t :: %__MODULE__{
    :"url" => String.t | nil,
    :"content_type" => String.t | nil,
    :"sha256" => String.t | nil,
    :"size" => integer() | nil
  }
end

defimpl Poison.Decoder, for: TelnyxAPI.Model.OutboundMessagePayloadMedia do
  def decode(value, _options) do
    value
  end
end

