# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule TelnyxAPI.Model.OutboundMessagePayloadFrom do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"phone_number",
    :"carrier",
    :"line_type"
  ]

  @type t :: %__MODULE__{
    :"phone_number" => String.t | nil,
    :"carrier" => String.t | nil,
    :"line_type" => String.t | nil
  }
end

defimpl Poison.Decoder, for: TelnyxAPI.Model.OutboundMessagePayloadFrom do
  def decode(value, _options) do
    value
  end
end

