# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule TelnyxAPI.Model.OutboundMessageEventMeta do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"attempt",
    :"delivered_to"
  ]

  @type t :: %__MODULE__{
    :"attempt" => integer() | nil,
    :"delivered_to" => String.t | nil
  }
end

defimpl Poison.Decoder, for: TelnyxAPI.Model.OutboundMessageEventMeta do
  def decode(value, _options) do
    value
  end
end

