# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule TelnyxAPI.Model.OutboundMessageEvent do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"data",
    :"meta"
  ]

  @type t :: %__MODULE__{
    :"data" => TelnyxAPI.Model.OutboundMessage.t | nil,
    :"meta" => TelnyxAPI.Model.OutboundMessageEventMeta.t | nil
  }
end

defimpl Poison.Decoder, for: TelnyxAPI.Model.OutboundMessageEvent do
  import TelnyxAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"data", :struct, TelnyxAPI.Model.OutboundMessage, options)
    |> deserialize(:"meta", :struct, TelnyxAPI.Model.OutboundMessageEventMeta, options)
  end
end

