# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule TelnyxAPI.Model.ParticipantConference do
  @moduledoc """
  Info about the conference that the participant is in
  """

  @derive [Poison.Encoder]
  defstruct [
    :"id",
    :"name"
  ]

  @type t :: %__MODULE__{
    :"id" => String.t | nil,
    :"name" => String.t | nil
  }
end

defimpl Poison.Decoder, for: TelnyxAPI.Model.ParticipantConference do
  def decode(value, _options) do
    value
  end
end

