# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule TelnyxAPI.Model.PhoneNumberWithMessagingSettings do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"record_type",
    :"id",
    :"phone_number",
    :"messaging_profile_id",
    :"created_at",
    :"updated_at",
    :"country_code",
    :"type",
    :"health",
    :"eligible_messaging_products",
    :"traffic_type",
    :"messaging_product",
    :"features"
  ]

  @type t :: %__MODULE__{
    :"record_type" => String.t | nil,
    :"id" => String.t | nil,
    :"phone_number" => String.t | nil,
    :"messaging_profile_id" => String.t | nil,
    :"created_at" => DateTime.t | nil,
    :"updated_at" => DateTime.t | nil,
    :"country_code" => String.t | nil,
    :"type" => String.t | nil,
    :"health" => TelnyxAPI.Model.NumberHealthMetrics.t | nil,
    :"eligible_messaging_products" => [String.t] | nil,
    :"traffic_type" => String.t | nil,
    :"messaging_product" => String.t | nil,
    :"features" => TelnyxAPI.Model.PhoneNumberWithMessagingSettingsFeatures.t | nil
  }
end

defimpl Poison.Decoder, for: TelnyxAPI.Model.PhoneNumberWithMessagingSettings do
  import TelnyxAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"health", :struct, TelnyxAPI.Model.NumberHealthMetrics, options)
    |> deserialize(:"features", :struct, TelnyxAPI.Model.PhoneNumberWithMessagingSettingsFeatures, options)
  end
end

