# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule TelnyxAPI.Model.PhoneNumberWithMessagingSettingsFeatures do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"sms",
    :"mms"
  ]

  @type t :: %__MODULE__{
    :"sms" => TelnyxAPI.Model.MessagingFeatureSet.t | nil,
    :"mms" => TelnyxAPI.Model.MessagingFeatureSet.t | nil
  }
end

defimpl Poison.Decoder, for: TelnyxAPI.Model.PhoneNumberWithMessagingSettingsFeatures do
  import TelnyxAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"sms", :struct, TelnyxAPI.Model.MessagingFeatureSet, options)
    |> deserialize(:"mms", :struct, TelnyxAPI.Model.MessagingFeatureSet, options)
  end
end

