# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule TelnyxAPI.Model.Queue do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"record_type",
    :"id",
    :"name",
    :"created_at",
    :"updated_at",
    :"current_size",
    :"max_size",
    :"average_wait_time_secs"
  ]

  @type t :: %__MODULE__{
    :"record_type" => String.t,
    :"id" => String.t,
    :"name" => String.t,
    :"created_at" => String.t,
    :"updated_at" => String.t,
    :"current_size" => integer(),
    :"max_size" => integer(),
    :"average_wait_time_secs" => integer()
  }
end

defimpl Poison.Decoder, for: TelnyxAPI.Model.Queue do
  def decode(value, _options) do
    value
  end
end

