# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule TelnyxAPI.Model.Recording do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"record_type",
    :"id",
    :"created_at",
    :"updated_at",
    :"recording_started_at",
    :"recording_ended_at",
    :"duration_millis",
    :"status",
    :"channels",
    :"source",
    :"conference_id",
    :"call_leg_id",
    :"call_session_id",
    :"download_urls"
  ]

  @type t :: %__MODULE__{
    :"record_type" => String.t,
    :"id" => String.t,
    :"created_at" => String.t,
    :"updated_at" => String.t,
    :"recording_started_at" => String.t,
    :"recording_ended_at" => String.t,
    :"duration_millis" => integer(),
    :"status" => String.t,
    :"channels" => String.t,
    :"source" => String.t,
    :"conference_id" => String.t | nil,
    :"call_leg_id" => String.t | nil,
    :"call_session_id" => String.t | nil,
    :"download_urls" => TelnyxAPI.Model.RecordingDownloadUrls.t
  }
end

defimpl Poison.Decoder, for: TelnyxAPI.Model.Recording do
  import TelnyxAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"download_urls", :struct, TelnyxAPI.Model.RecordingDownloadUrls, options)
  end
end

