# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule TelnyxAPI.Model.ReferRequest do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"sip_address",
    :"client_state",
    :"command_id",
    :"custom_headers",
    :"sip_auth_username",
    :"sip_auth_password"
  ]

  @type t :: %__MODULE__{
    :"sip_address" => String.t,
    :"client_state" => String.t | nil,
    :"command_id" => String.t | nil,
    :"custom_headers" => [TelnyxAPI.Model.CustomSipHeader.t] | nil,
    :"sip_auth_username" => String.t | nil,
    :"sip_auth_password" => String.t | nil
  }
end

defimpl Poison.Decoder, for: TelnyxAPI.Model.ReferRequest do
  import TelnyxAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"custom_headers", :list, TelnyxAPI.Model.CustomSipHeader, options)
  end
end

