# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule TelnyxAPI.Model.ReplacedLinkClick do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"record_type",
    :"url",
    :"to",
    :"message_id",
    :"time_clicked"
  ]

  @type t :: %__MODULE__{
    :"record_type" => String.t | nil,
    :"url" => String.t | nil,
    :"to" => String.t | nil,
    :"message_id" => String.t | nil,
    :"time_clicked" => DateTime.t | nil
  }
end

defimpl Poison.Decoder, for: TelnyxAPI.Model.ReplacedLinkClick do
  def decode(value, _options) do
    value
  end
end

