# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule TelnyxAPI.Model.ShortCode do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"record_type",
    :"id",
    :"short_code",
    :"country_code",
    :"messaging_profile_id",
    :"created_at",
    :"updated_at"
  ]

  @type t :: %__MODULE__{
    :"record_type" => String.t | nil,
    :"id" => String.t | nil,
    :"short_code" => String.t | nil,
    :"country_code" => String.t | nil,
    :"messaging_profile_id" => String.t | nil,
    :"created_at" => DateTime.t | nil,
    :"updated_at" => DateTime.t | nil
  }
end

defimpl Poison.Decoder, for: TelnyxAPI.Model.ShortCode do
  def decode(value, _options) do
    value
  end
end

