# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule TelnyxAPI.Model.SpeakRequest do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"payload",
    :"payload_type",
    :"service_level",
    :"stop",
    :"voice",
    :"language",
    :"client_state",
    :"command_id"
  ]

  @type t :: %__MODULE__{
    :"payload" => String.t,
    :"payload_type" => String.t | nil,
    :"service_level" => String.t | nil,
    :"stop" => String.t | nil,
    :"voice" => String.t,
    :"language" => String.t,
    :"client_state" => String.t | nil,
    :"command_id" => String.t | nil
  }
end

defimpl Poison.Decoder, for: TelnyxAPI.Model.SpeakRequest do
  def decode(value, _options) do
    value
  end
end

