# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule TelnyxAPI.Model.StartRecordingRequest do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"format",
    :"channels",
    :"client_state",
    :"command_id",
    :"play_beep",
    :"max_length"
  ]

  @type t :: %__MODULE__{
    :"format" => String.t,
    :"channels" => String.t,
    :"client_state" => String.t | nil,
    :"command_id" => String.t | nil,
    :"play_beep" => boolean() | nil,
    :"max_length" => integer() | nil
  }
end

defimpl Poison.Decoder, for: TelnyxAPI.Model.StartRecordingRequest do
  def decode(value, _options) do
    value
  end
end

