# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule TelnyxAPI.Model.StartForkingRequest do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"target",
    :"rx",
    :"stream_type",
    :"tx",
    :"client_state",
    :"command_id"
  ]

  @type t :: %__MODULE__{
    :"target" => String.t | nil,
    :"rx" => String.t | nil,
    :"stream_type" => String.t | nil,
    :"tx" => String.t | nil,
    :"client_state" => String.t | nil,
    :"command_id" => String.t | nil
  }
end

defimpl Poison.Decoder, for: TelnyxAPI.Model.StartForkingRequest do
  def decode(value, _options) do
    value
  end
end

