# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule TelnyxAPI.Model.TranscriptionPayload do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"call_control_id",
    :"call_leg_id",
    :"call_session_id",
    :"client_state",
    :"connection_id",
    :"transcription_data"
  ]

  @type t :: %__MODULE__{
    :"call_control_id" => String.t | nil,
    :"call_leg_id" => String.t | nil,
    :"call_session_id" => String.t | nil,
    :"client_state" => String.t | nil,
    :"connection_id" => String.t | nil,
    :"transcription_data" => TelnyxAPI.Model.TranscriptionPayloadTranscriptionData.t | nil
  }
end

defimpl Poison.Decoder, for: TelnyxAPI.Model.TranscriptionPayload do
  import TelnyxAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"transcription_data", :struct, TelnyxAPI.Model.TranscriptionPayloadTranscriptionData, options)
  end
end

