# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule TelnyxAPI.Model.TranscriptionPayloadTranscriptionData do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"confidence",
    :"transcript"
  ]

  @type t :: %__MODULE__{
    :"confidence" => float() | nil,
    :"transcript" => String.t | nil
  }
end

defimpl Poison.Decoder, for: TelnyxAPI.Model.TranscriptionPayloadTranscriptionData do
  def decode(value, _options) do
    value
  end
end

