# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule TelnyxAPI.Model.TranscriptionStartRequest do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"language",
    :"client_state",
    :"command_id"
  ]

  @type t :: %__MODULE__{
    :"language" => String.t | nil,
    :"client_state" => String.t | nil,
    :"command_id" => String.t | nil
  }
end

defimpl Poison.Decoder, for: TelnyxAPI.Model.TranscriptionStartRequest do
  def decode(value, _options) do
    value
  end
end

