# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule TelnyxAPI.Model.TransferCallRequestAnsweringMachineDetectionConfig do
  @moduledoc """
  Optional configuration parameters to modify 'answering_machine_detection' performance.
  """

  @derive [Poison.Encoder]
  defstruct [
    :"total_analysis_time_millis",
    :"after_greeting_silence_millis",
    :"between_words_silence_millis",
    :"greeting_duration_millis",
    :"initial_silence_millis",
    :"maximum_number_of_words",
    :"maximum_word_length_millis",
    :"silence_threshold",
    :"greeting_total_analysis_time_millis",
    :"greeting_silence_duration_millis"
  ]

  @type t :: %__MODULE__{
    :"total_analysis_time_millis" => integer() | nil,
    :"after_greeting_silence_millis" => integer() | nil,
    :"between_words_silence_millis" => integer() | nil,
    :"greeting_duration_millis" => integer() | nil,
    :"initial_silence_millis" => integer() | nil,
    :"maximum_number_of_words" => integer() | nil,
    :"maximum_word_length_millis" => integer() | nil,
    :"silence_threshold" => integer() | nil,
    :"greeting_total_analysis_time_millis" => integer() | nil,
    :"greeting_silence_duration_millis" => integer() | nil
  }
end

defimpl Poison.Decoder, for: TelnyxAPI.Model.TransferCallRequestAnsweringMachineDetectionConfig do
  def decode(value, _options) do
    value
  end
end

