# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule TelnyxAPI.Model.UpdatePhoneNumberMessagingSettingsRequest do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"messaging_profile_id",
    :"messaging_product"
  ]

  @type t :: %__MODULE__{
    :"messaging_profile_id" => String.t | nil,
    :"messaging_product" => String.t | nil
  }
end

defimpl Poison.Decoder, for: TelnyxAPI.Model.UpdatePhoneNumberMessagingSettingsRequest do
  def decode(value, _options) do
    value
  end
end

