# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule TelnyxAPI.Model.UpdateConferenceRequest do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"call_control_id",
    :"command_id",
    :"supervisor_role",
    :"whisper_call_control_ids"
  ]

  @type t :: %__MODULE__{
    :"call_control_id" => String.t,
    :"command_id" => String.t | nil,
    :"supervisor_role" => String.t,
    :"whisper_call_control_ids" => [String.t] | nil
  }
end

defimpl Poison.Decoder, for: TelnyxAPI.Model.UpdateConferenceRequest do
  def decode(value, _options) do
    value
  end
end

