# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule TelnyxAPI.Model.UrlShortenerSettings do
  @moduledoc """
  The URL shortener feature allows automatic replacement of URLs that were generated using a public URL shortener service. Some examples include bit.do, bit.ly, goo.gl, ht.ly, is.gd, ow.ly, rebrand.ly, t.co, tiny.cc, and tinyurl.com. Such URLs are replaced with with links generated by Telnyx. The use of custom links can improve branding and message deliverability.  To disable this feature, set the object field to `null`. 
  """

  @derive [Poison.Encoder]
  defstruct [
    :"domain",
    :"prefix",
    :"replace_blacklist_only",
    :"send_webhooks"
  ]

  @type t :: %__MODULE__{
    :"domain" => String.t,
    :"prefix" => String.t | nil,
    :"replace_blacklist_only" => boolean() | nil,
    :"send_webhooks" => boolean() | nil
  }
end

defimpl Poison.Decoder, for: TelnyxAPI.Model.UrlShortenerSettings do
  def decode(value, _options) do
    value
  end
end

