# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule TelnyxAPI.Api.CallInformation do
  @moduledoc """
  API calls for all endpoints tagged `CallInformation`.
  """

  alias TelnyxAPI.Connection
  import TelnyxAPI.RequestBuilder


  @doc """
  Retrieve a call status
  Returns the status of a call (data is available 10 minutes after call ended).

  ## Parameters

  - connection (TelnyxAPI.Connection): Connection to server
  - call_control_id (String.t): Unique identifier and token for controlling the call
  - opts (KeywordList): [optional] Optional parameters
  ## Returns

  {:ok, TelnyxAPI.Model.RetrieveCallStatusResponse.t} on success
  {:error, Tesla.Env.t} on failure
  """
  @spec retrieve_call_status(Tesla.Env.client, String.t, keyword()) :: {:ok, TelnyxAPI.Model.Errors.t} | {:ok, TelnyxAPI.Model.RetrieveCallStatusResponse.t} | {:error, Tesla.Env.t}
  def retrieve_call_status(connection, call_control_id, _opts \\ []) do
    %{}
    |> method(:get)
    |> url("/calls/#{call_control_id}")
    |> Enum.into([])
    |> (&Connection.request(connection, &1)).()
    |> evaluate_response([
      { 200, %TelnyxAPI.Model.RetrieveCallStatusResponse{}},
      { :default, %TelnyxAPI.Model.Errors{}}
    ])
  end
end
